kek

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -33,14 +33,23 @@ jobs:
           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
 
+      - name: Get EC2 Public DNS
+        id: get-ec2-dns
+        run: |
+          INSTANCE_PUBLIC_DNS=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query "Reservations[0].Instances[0].PublicDnsName" --output text)
+          echo "INSTANCE_PUBLIC_DNS=$INSTANCE_PUBLIC_DNS" >> $GITHUB_ENV
+          echo "Public DNS: $INSTANCE_PUBLIC_DNS"
+
       - name: Deploy to EC2
         env:
-          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
+          INSTANCE_PUBLIC_DNS: ${{ env.INSTANCE_PUBLIC_DNS }}
           EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
           EC2_USER: ${{ secrets.EC2_USER }}
         run: |
-          # Get the public DNS of the EC2 instance
-          INSTANCE_PUBLIC_DNS=$(aws ec2 describe-instances --instance-ids $EC2_INSTANCE_ID --query "Reservations[0].Instances[0].PublicDnsName" --output text)
+          if [ -z "$INSTANCE_PUBLIC_DNS" ]; then
+            echo "Error: INSTANCE_PUBLIC_DNS is empty."
+            exit 1
+          fi
 
           # Deploy the Docker container to EC2
           ssh -i $EC2_SSH_KEY $EC2_USER@$INSTANCE_PUBLIC_DNS << 'EOF'
