test

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -50,6 +50,11 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
           script: |
-            cd ./app/
-            docker-compose -f docker-compose.prod.yaml pull
-            docker-compose -f docker-compose.prod.yaml up -d
+            cd app/
+            if [ -f docker-compose.prod.yaml ]; then
+              docker-compose -f docker-compose.prod.yaml pull
+              docker-compose -f docker-compose.prod.yaml up -d
+            else
+              echo "File docker-compose.prod.yaml not found"
+              exit 1
+            fi
